<?php
$all_places = array("achern", "adelshofen", "adelshofen (baden)", "affaltrach", "albersweiler", "allerheiligen/oppen", "allerheiligen/oppen.", "alpirsbach", "alsterweiler", "altdorf", 
"altlußheim", "altschweier", "angelbachtal", "annweiler", "appenhofen", "appenweier", "arnbach", "arzheim", "au am rhein", "auerbach", 
"bad bergzabern", "bad herrenalb", "bad liebenzell", "bad rotenfels", "bad schönborn", "bad teinach", "bad teinach-zavelstein", "bad wildbad", "baden-baden", "bahnbrücken", 
"baiersbronn", "balg", "balzhofen", "balzhofen (baden)", "barbelroth", "bauerbach", "bauschlott", "beiertheim", "beinberg", "bellheim", 
"berg", "berghausen", "berghausen (pfalz)", "berghausen (pfinztal)", "bergwald", "bermersbach", "bernbach", "besenfeld", "biberach", "biberach (baden)", 
"bieselsberg", "bietigheim", "bietigheim (kr lb)", "bietigheim (kr. lb)", "bietigheim (ra)", "bietigheim-bissingen", "bilfingen", "billigheim", "billigheim-ingenheim", "bindersbach", 
"birkenfeld", "birkenhördt", "birkweiler", "bischweier", "bittelbronn", "bittelbronn (horb)", "bitzfeld", "blankenborn", "blankenloch", "bobenthal", 
"bohlsbach", "bornheim", "brandmatt", "breithurst", "bretten", "bretzfeld", "bruchhausen", "bruchsal", "bruchw-bärenb", "bruchw.-bärenb.", 
"brötzingen", "bulach", "bundenthal", "burbach", "burrweiler", "busenbach", "busenberg", "böbingen", "böchingen", "böckingen", 
"böllenborn", "büchelberg", "büchenau", "büchig", "bühl", "bühlerhöhe", "bühlertal", "calmbach", "calw", "christophstal", 
"conweiler", "corres", "dahn", "dammheim", "darmsbach", "darstein", "darstein (pfalz)", "daxlanden", "dennach", "dennach (württ)", 
"dennjächt", "dernbach", "dettenheim", "diedelsheim", "diedesfeld", "diefenbach", "diefenbach (württ)", "dierbach", "dietenhausen", "dietlingen", 
"dillweißenstein", "dimbach", "dimbach (pfalz)", "dobel", "dornstetten", "dornstetten (württ)", "dreihof", "drusenheim", "dudenhofen", "dudenhofen (speyer)", 
"durlach", "durmersheim", "duttweiler", "dörrenbach", "dühren", "dühren (baden)", "dürrbaden", "dürrenbüchig", "dürrn", "ebersteinburg", 
"ebhausen", "edenkoben", "edesheim", "eggenst-leopoldshf", "eggenst.-leopoldshf.", "eggenstein", "eichelberg", "eichtersheim", "eisental", "eisental (baden)", 
"eisingen", "elchesheim-illingen", "ellhofen", "ellhofen (württ)", "ellmendingen", "elsenz", "emilienruhe", "emmingen", "enzberg", "enzklösterle", 
"eppingen", "erbersbronn", "erlenbach", "erlenbach (dahn)", "ernstmühl", "ersingen", "eschbach", "eschelbach", "eschelbach (baden)", "eschenau", 
"eschenau (obersulm)", "essingen", "ettlingen", "ettlingenweier", "etzenrot", "eutingen", "eutingen im gäu", "eußerthal", "fassenteich", "fautenbach", 
"feldrennach", "fischweier", "flehingen", "flemlingen", "forbach", "forchheim", "forst", "frankenthal", "frankenthal (pfalz)", "frankweiler", 
"frauenalb", "freckenfeld", "freimersheim", "freiolsheim", "freisbach", "freistett", "freudenstadt", "freudenstein", "friedrichstal", "furschenbach", 
"förch", "gaggenau", "gaistal", "gallenbach", "gausbach", "geinsheim", "geinsheim (pfalz)", "gemmingen", "gengenbach", "germersheim", 
"gernsbach", "geroldsau", "gleishorbach", "gleisweiler", "gleiszellen", "gochsheim", "godramstein", "gommersheim", "gompelscheuer", "gondelsheim", 
"gossersweiler", "gossersweiler-stein", "graben", "graben-neudorf", "grauelsbaum", "greffern", "großfischlingen", "großvillars", "gräfenhausen", "gräfenhausen (pfalz)", 
"grötzingen", "grüntal", "grüntal (württ)", "grünwettersbach", "göbrichen", "göcklingen", "gölshausen", "gündelbach", "haft", "hagenbach", 
"hagsfeld", "hainfeld", "halberstung", "halbmeil", "hambach", "hambach (weinstr)", "hambrücken", "hanhofen", "hardtwald", "hardtwald (kr ra)", 
"harthausen", "harthausen (pfalz)", "haslach im kinzigtal", "hatzenbühl", "hatzenweier", "haueneberstein", "hauenstein", "hausach", "hayna", "heidelberg", 
"heidelsheim", "heilbronn", "heiligenstein", "heiligenstein (pfalz)", "helmlingen", "helmsheim", "hergersweiler", "herrenwies", "herxheim", "herxheimweyher", 
"heselbach", "heselbach (württ)", "hessental", "heuchelh-klingen", "heuchelh.-klingen", "hildmannsfeld", "hilpertsau", "hilsbach", "hilsbach (baden)", "hinterlangenbach", 
"hinterweidenthal", "hirsau", "hochdorf", "hochfeld", "hochstadt", "hochstetten", "hockenheim", "hofstätten", "hofstätten (pfalz)", "hohenklingen", 
"hohenwettersbach", "horb a neckar", "hub", "hundsbach", "hundseck", "huttenheim", "huttenheim (baden)", "huzenbach", "höfen", "hörden", 
"hördt", "hördt (pfalz)", "hügelsheim", "iffezheim", "igelsberg/freudenst", "igelsberg/freudenst.", "ilbesheim", "illingen", "impflingen", "ingenheim", 
"ingenheim (pfalz)", "insheim", "ispringen", "ittersbach", "ittlingen", "jockgrim", "jöhlingen", "kaiserbacher mühle", "kaisermühle", "kaltenbronn", 
"kandel", "kapellen", "kapellen-drusweiler", "kappelrodeck", "kappelwindeck", "kapsweyer", "karlsbad", "karlsdorf", "karlsdorf-neuthard", "karlsruhe", 
"kartung", "keltern", "kentheim", "kieselbronn", "kirchheim", "kirchheim (hd)", "kirrlach", "kirrweiler", "kirschbaumwasen", "kleinfischlingen", 
"kleingartach", "kleinsteinbach/baden", "kleinvillars", "kleinwildbad", "klingen", "klingenmünster", "klosterreichenbach", "kniebis/freudenstadt", "knielingen", "knittelsheim", 
"knittlingen", "knöringen", "kraichtal", "kronau", "kuhardt", "kuppenheim", "kämpfelbach", "königsbach", "kürnbach", "lachen", 
"lachen (pfalz)", "landau", "landshausen", "langenalb", "langenbrand", "langenbrücken", "langensteinbach", "lauf", "lautenbach", "lauterbourg", 
"lauterschwan", "leiberstung", "leimen", "leimen (baden)", "leimersheim", "leingarten", "leinsweiler", "leinsweilerhof", "leonbronn", "leopoldshafen", 
"lichtenau", "lichtental", "liedolsheim", "lienzingen", "lierbach", "lingenfeld", "linkenh-hochstet", "linkenh.-hochstet.", "linkenheim", "loffenau", 
"loßburg-rodt", "ludwigsburg", "ludwigshafen", "ludwigshafen (rhein)", "lug", "lustadt", "maikammer", "mainz", "maisenbach", "malsch", 
"malsch (wiesloch)", "malschbach", "malschenberg", "mannheim", "marxzell", "massenbach", "massenbach (württ)", "massenbachhausen", "maulbronn", "maximiliansau", 
"memprechtshofen", "menzingen", "michelbach", "michelfeld", "michelfeld (angelb)", "michelfeld (angelb.)", "minderslachen", "minfeld", "mingolsheim", "mittelenztal", 
"mittellangenbach", "monbachtal", "moos", "moosbronn", "muckenschopf", "muggensturm", "mummelsee", "mutschelbach", "mörlheim", "mörsch", 
"mörzheim", "mühlacker", "mühlbach", "mühlbach (eppingen)", "mühlburg", "mühlhausen", "mühlhausen (heidelb)", "mühlhofen", "müllhofen", "münchweiler", 
"münchweiler (rodalb)", "münzesheim", "n, n", "nagold", "neckarau", "neibsheim", "neubulach", "neuburg", "neuburgweier", "neudorf", 
"neuenbürg", "neuenstein", "neuenstein (württ)", "neulauterburg", "neulingen", "neulingen (enzkr)", "neulußheim", "neupotz", "neureut", "neusatz", 
"neusatz (herrenalb)", "neustadt", "neustadt (weinstraße)", "neuthard", "neuweier", "niebelsbach", "niederbühl", "niederhofen", "niederhofen (württ)", "niederotterbach", 
"niederschlettenbach", "niederweier", "niefern", "niefern-Öschelbronn", "nonnenmiß", "nußbaum", "nußdorf", "nöttingen", "oberachern", "oberacker", 
"oberbeuern", "oberbruch", "oberderdingen", "obergrombach", "oberhausen", "oberhofen", "oberhsn-rheinhausen", "oberhsn.-rheinhausen", "oberlengenhardt", "oberndorf", 
"obernhausen", "oberotterbach", "oberreut", "obersasbach", "oberschlettenbach", "obersulm", "obertsrot", "oberweier", "oberweier (ettlingen)", "oberweier (murgtal)", 
"oberöwisheim", "ochsenburg", "odenheim", "offenbach", "offenburg", "oftersheim", "oppenau", "ottenau", "ottenhausen", "ottenhausen (württ)", 
"ottenhöfen", "ottersdorf", "ottersheim", "ottersweier", "palmbach", "pfaffenrot", "pfinztal", "pfinzweiler", "pforzheim", "philippsburg", 
"pirmasens", "pleisweiler", "plittersdorf", "poppeltal", "queichhambach", "queichheim", "ramberg", "ramberg (pfalz)", "ranschbach", "rastatt", 
"rauenberg", "rauenberg (wiesloch)", "rauental", "raumünzach", "rechtenbach", "reichenbach", "reichenbach (dahn)", "reichental", "reihen", "reisdorf", 
"remchingen", "renchen", "rettigheim", "rheinau", "rheinau (baden)", "rheinau (ma)", "rheinhausen", "rheinmünster", "rheinsheim", "rheinstetten", 
"rheinzabern", "rhodt", "rhodt (rietburg)", "richen", "richen (b eppingen)", "riegel", "rinklingen", "rinnthal", "rintheim", "rittersbach", 
"rodalben", "rohnbach", "rohrbach", "rohrbach (eppingen)", "roschbach", "rot", "rot (st leon)", "rot (st. leon)", "rotenbach", "rotenbach (enzkr)", 
"rotensol", "rotfelden", "ruhestein", "ruit", "rußheim", "römerberg", "römerberg (pfalz)", "röt", "rülzheim", "rüppurr", 
"sachsenheim", "sachsenheim (württ)", "sand", "sandweier", "sarnstall", "sasbach", "sasbachried", "sasbachwalden", "schaidt", "scheibenhardt", 
"schenkenzell", "scheppach", "scheppach (bretzfeld)", "scherrhof", "scherzheim", "scheuern", "schielberg", "schifferstadt", "schiftung", "schiltach", 
"schindhard", "schluttenbach", "schmalbach", "schmie", "schopfloch", "schopfloch (b freudenstadt)", "schwaigern", "schwaigern (württ)", "schwanheim", "schwanheim (pfalz)", 
"schwann", "schwarzach", "schwarzenberg", "schwegenheim", "schweigen", "schweighofen", "schwetzingen", "schwäbisch hall", "schöllbronn", "schömberg", 
"schönenberg", "schönmünzach", "schützingen", "seebach", "seewald", "seibelseckle", "selbach", "seltz", "sersheim", "siebeldingen", 
"silz", "singen", "sinsheim", "sinsheim (elsenz)", "sinzheim", "sondernheim", "spessart", "speyer", "speyerdorf", "speyerdorf (lachen)", 
"spielberg", "spirkelbach", "sprantal", "sprollenhaus", "spöck", "st germanshof", "st ilgen b heidelbg", "st johann", "st leon-rot", "st martin", 
"st. germanshof", "st. johann", "st. leon-rot", "st. martin", "staffort", "staufenberg", "stebbach", "stein", "steinach", "steinbach", 
"steinfeld", "steinmauern", "steinmauern (kr ra)", "steinsfurt", "steinweiler", "sternenfels", "stetten", "stettfeld", "stollhofen", "straubenhardt", 
"stupferich", "stutensee", "stuttgart", "sulzbach", "sulzbach (gaggenau)", "sulzbach (malsch)", "sulzfeld", "söllingen", "söllingen (pfinztal)", "söllingen (rheinm)", 
"söllingen (rheinm.)", "sülzbach", "tiefenbach", "tübingen", "ubstadt", "ubstadt-weiher", "ulm", "untergrombach", "unterlengenhardt", "unterreichenbach", 
"unterstmatt", "unterwasser", "unteröwisheim", "unzhurst", "urloffen", "urnagold", "vaihingen", "vaihingen (enz)", "varnhalt", "venningen", 
"vimbuch", "vollmersweiler", "vorderlangenbach", "vorderweidenthal", "völkersbach", "völkersweiler", "waghäusel", "waldangelloch", "waldbronn", "waldenburg", 
"waldenburg (württ)", "waldhambach", "waldhambach (pfalz)", "waldmatt", "waldprechtsweier", "waldrohrbach", "waldstadt", "walsheim", "walsheim (pfalz)", "walzbachtal", 
"weiher", "weiler", "weiler (sinsheim)", "weingarten", "weingarten (baden)", "weingarten (pfalz)", "weinsberg", "weisenbach", "weitenung", "welschhof", 
"wernersberg", "westheim", "weyher", "wiesental", "wieslensdorf", "wiesloch", "wildberg", "wilferdingen", "wilgartswiesen", "willsbach", 
"winden", "windschläg", "wintersdorf", "wissembourg", "wolfach", "wolfartsweier", "wollmesheim", "worms", "wörth", "wöschbach", 
"wössingen", "würmersheim", "zaberfeld", "zainen", "zaisenhausen", "zaisersweiher", "zeiskam", "zeutern", "zimmern", "zwickgabel", 
"Öhringen", "Ölbronn", "Ölbronn-dürrn", "Önsbach", "Östringen", "Ötigheim", "Ötisheim");
$all_names = array("a-schweitzer-schule", "a-stifter-straße", "a.-schweitzer-schule", "a.-stifter-straße", "aalkistensee", "ab bosenst/kernhof", "ab heimbronner hof", "ab maisenb sägem", "ab unterlengenhardt", "ab. bosenst./kernhof", 
"ab. heimbronner hof", "ab. maisenb. sägem.", "ab. unterlengenhardt", "abz schwarzenbg", "abz. schwarzenbg.", "abzw affental", "abzw amicitia-hütte", "abzw bahnhof", "abzw breithurst", "abzw burg", 
"abzw burg windeck", "abzw buschmühle", "abzw dimbach", "abzw dörrenbergstr", "abzw dürrn", "abzw essingen", "abzw gleisweiler", "abzw grüntal (b)", "abzw hatzenweier", "abzw heimigstraße", 
"abzw hohritt", "abzw igelsberg", "abzw kettelerstraße", "abzw ludwigshöhe", "abzw neuhof", "abzw niederotterbach", "abzw ottenhöfen", "abzw rotfelden", "abzw ruit", "abzw sasbachried", 
"abzw scheuern", "abzw schule", "abzw siebeld hütte", "abzw unteres gaistal", "abzw waldrohrbach", "abzw weissenst hof", "abzw wernersberg", "abzw westbahnhof", "abzw winden", "abzw zainen", 
"abzw. affental", "abzw. amicitia-hütte", "abzw. bahnhof", "abzw. breithurst", "abzw. burg", "abzw. burg windeck", "abzw. buschmühle", "abzw. dimbach", "abzw. dörrenbergstr", "abzw. dürrn", 
"abzw. essingen", "abzw. gleisweiler", "abzw. grüntal", "abzw. grüntal (b)", "abzw. hatzenweier", "abzw. heimigstraße", "abzw. hohritt", "abzw. igelsberg", "abzw. kettelerstraße", "abzw. ludwigshöhe", 
"abzw. neuhof", "abzw. niederotterbach", "abzw. ottenhöfen", "abzw. rotfelden", "abzw. ruit", "abzw. sasbachried", "abzw. scheuern", "abzw. schule", "abzw. siebeld. hütte", "abzw. unteres gaistal", 
"abzw. waldrohrbach", "abzw. weissenst. hof", "abzw. wernersberg", "abzw. westbahnhof", "abzw. winden", "abzw. zainen", "abzw.b", "abzw.bahnhof", "abzw.favorite", "abzw.mörlheim", 
"abzw.winden", "abzwb", "abzwbahnhof", "abzweigung klingen", "abzwfavorite", "abzwmörlheim", "abzwwinden", "adler", "adlergasse", "adlerplatz", 
"adolf-bieringer-straße", "adolf-ehrmann-bad", "adolf-kolping-straße", "adventure golfpark", "ahornbrunnen", "ahornweg", "airpark eisstadion", "airpark terminal", "airpark verwaltung", "aitergrund", 
"akazienstraße", "akazienweg", "albert-braun-straße", "albert-einstein-straße", "albert-schweitzer-straße", "albgaubad", "albrecht-dürer-straße", "albtalbahnhof", "albtherme", "alexanderschanze", 
"allmend", "alois-degler-straße", "alte bahnmeisterei", "alte dobler straße", "alte kirche", "alte kreisstraße", "alte landstraße", "alte pforzheimer straße", "alte post", "alte schule", 
"alte steiner straße", "altenheim", "altenpflegeheim schafberg", "altenzentrum", "alter bahnhof", "alter kindergarten", "alter meßplatz", "altes feuerwehrhaus", "altes neffwerk/wilhelmstraße", "altes rathaus", 
"altes schloß", "altes schulhaus", "altes stadtbad", "althof", "altrheinbrücke", "am bachkanal", "am bürgerpark", "am dreschplatz", "am essig", "am froschbächle", 
"am hang", "am hardtwald", "am hasenspiel", "am hasenwäldchen", "am hausberg", "am heegwald", "am hubengut", "am hänfig", "am kirchberg", "am köpfel", 
"am leitzelbach", "am lindenbosch", "am lindscharren", "am mantel", "am markbach", "am neubruch", "am neugarten", "am rebhang", "am rosenhang", "am sang", 
"am see", "am skihang", "am sportplatz", "am stackler", "am stadion", "am steigert", "am steingraben", "am unkenfunk", "am vogelstock", "am weißen stein", 
"am wiesental", "am wilden mann", "am zinken", "amalienhof", "amalienstraße", "amthof", "an der fayence", "an der ochsenstraße", "an der pfinz", "an der steige", 
"an der tagweide", "an der trift", "andreas-hofer-straße", "ankerstraße", "anne-frank-schule", "anne-frank-straße", "annweiler straße", "annweilerstraße", "apotheke", "appenhofen", 
"appenweierstraße", "arbeiterheim", "arbeitsagentur", "arbeitsamt", "arndtstraße/berliner straße", "asamstraße", "aschenplatz", "au im murgtal", "aubrücke", "auer straße", 
"auer straße/dr.willmar schwabe", "auer straße/drwillmar schwabe", "auf der römerstraße", "aug-croissant-straße/bbs", "aug-dosenbach-straße", "aug.-croissant-straße/bbs", "aug.-dosenbach-straße", "augartenstraße", "augrund", "augspurgermühle", 
"augsteiner", "august-bebel-straße", "august-macke-straße", "augustaplatz museum burda", "augustenberg", "aussiedlerhof", "aussiedlerhöfe", "autobahnkirche", "autohalle", "autohaus schleeh", 
"auweg", "b", "b/abzw.reichental", "b/abzwreichental", "bach", "bach west", "bachallee", "bachenweg", "bachschloßschule", "bachstraße", 
"backhaus", "bad schönborn süd", "bad schönborn-kronau bf", "bad teinach bahnhof", "badallee", "badener brücke", "badeniaplatz", "badenstraße", "badeparadies", "badepark", 
"badischer hof", "badner halle", "badstraße", "bahnhof", "bahnhof (db)", "bahnhof / rotherma", "bahnhof nord", "bahnhof ort", "bahnhof ost", "bahnhof west", 
"bahnhofstraße", "bahnholzstraße", "bahnübergang", "bais", "bamt", "bannholz", "bannwaldallee", "bannwaldstraße", "barbaraweg", "barbarossaplatz", 
"bastwald", "battstraße", "bauerbacher straße", "bauernfeldstraße", "baum", "baumackerstraße", "baumeisterstraße", "beethoven-/r-schumann-straße", "beethoven-/r.-schumann-straße", "beethovenstraße", 
"beiertheim west", "beinle", "belchenplatz", "bellheimer straße", "benzstraße", "berghof", "bergschule", "bergstraße", "bergwald", "berliner ring", 
"berliner straße", "bernbacher weg", "bernhard-lichtenberg-straße", "bernhardush./kaiserlindenw.", "bernhardush/kaiserlindenw", "bernharduskapelle", "bernsteinstraße", "bertha-von-suttner-schule", "bertholdplatz", "berufsakademie", 
"berufsschule", "berufsschulzentrum", "berwartstein/seehof", "berwartsteinstraße", "bethel", "bethesda", "bethof", "betriebshof", "bg-chemie", "biberach", 
"biberach bahnhof", "biberstraße", "biblisweg", "bienwaldhalle", "bierbachstraße", "bildeiche", "bildungszentrum", "billensbacher", "bindersbach", "bindfadenfabrik", 
"binger straße", "birkenbuckel", "birkengrund", "birkenhof", "birkenhördt", "birkenstraße", "birkenwaldstraße", "birkenweg", "birkenweiher", "birnbaumweg", 
"bischenberg", "bischweierer straße", "bismarckstraße", "blanco verwaltung", "blanco werk iii", "blankenborn", "blankenlocher weg", "blattwiesenstraße", "bleichstraße", "blockhütte", 
"blohnstraße", "blume", "blumenstraße", "blütenstraße", "bobenthal", "bocksbergstraße", "bockstalstraße", "boosweg", "bosch", "boschbrücke", 
"brandmatt", "braun/lidl", "breit", "breite straße", "breitenackerweg", "breitenbrunnen", "breithurst", "breitmatt", "breitscheidstraße", "breslauer straße", 
"brettener straße", "breuerstraße", "brombachweg", "bruchsaler straße", "bruchweg", "brunnen", "brunnenhäusle", "brüchelwaldschule", "brüchlehöfe", "brücke", 
"brücke haft", "brücke l", "brückenstraße", "brückenwaage", "brühl", "brühlstraße", "brühlstraße mitte", "buchberg gymnasium", "buchberg/feldbergstraße", "buchenauerhof", 
"buchenweg", "buchgasse", "buchkopf", "bulach friedhof", "bulach west", "bunsenstraße", "burgstraße", "burgwiesen", "burrweiler mitte", "busbahnhof", 
"bussardweg", "buswendeplatz", "bußmatten i", "bußmatten ii", "bäderviertel", "bären", "bärenweg", "böllenborn", "büchelbergstraße", "büchenauer straße", 
"büchig", "büchiger allee", "bühlerhöhe/plättig", "bühlertalstr/hauptstr", "bühlertalstr/kappelwstraße", "bühlstraße", "bürgerhaus", "bürgerpark", "café jägersteig", "calwer straße", 
"campingplatz", "canadastraße", "candidusstraße", "cappel", "caracalla therme", "carl-benz-schule", "carl-benz-straße", "carl-orff-schule", "casimir-katz-straße", "central", 
"chennevieresplatz", "christophshof", "cité", "corres", "cuppamare", "daimler benz nord", "daimler-chrysler", "daimlerchrysler", "damianstor", "dammbergstraße", 
"dammerstock", "dammhof", "dammstraße", "dammweg", "dammühlstraße", "danziger platz", "danziger straße", "darstein", "demag", "denkmal", 
"denni", "derdinger straße", "descostraße", "deutsches tor", "deutschhof", "diehl", "dieselstraße", "dietlinger straße", "dimbach", "dittmannswiesen", 
"dobeltal", "dobeltalschule", "domherrenplatz", "donauschwabenstraße", "donaustraße", "dorf", "dorfbrunnen", "dorfgemeindehaus", "dorfgemeinschaftshaus", "dorfplatz", 
"dorfstraße", "dorfwiesenstraße", "dorfzentrum", "dornröschenweg", "dorschbergstraße", "dossentalstraße", "dr fecht waldheim", "dr schröder weg", "dr sommer", "dr-schleyer-straße", 
"dr. fecht waldheim", "dr. schröder weg", "dr. sommer", "dr.-schleyer-straße", "drachenfelsstraße", "drei buchen", "dreieichenkapelle", "dreimarkstein", "dreiröhrenbrunnen", "dreschhalle", 
"drosselweg", "dudenhofer straße", "dupont", "durlacher allee", "durlacher straße", "durlacher tor", "durmersheimer straße", "dörrenberg", "dührener straße", "dürrbachstraße", 
"dürrbaden", "dürrbaden (b)", "dürrenbüchig", "dürrenwettersbacher straße", "dürrner steigle", "dürrner straße", "e-blickle-straße", "e-fuchslocher-platz", "e-werk", "e.-blickle-straße", 
"e.-fuchslocher-platz", "ebertplatz", "ebertstraße", "eckenerstraße", "eckerlestraße", "edelbergstraße", "eggensteiner straße", "eggerten", "ehem abtei", "ehem. abtei", 
"eichelbergsiedlung", "eichelbergstraße", "eichenauer", "eichendorffgymnasium", "eichenplochhütte", "eichenwaldstraße", "eichenweg", "eichhalden", "eichholz", "eichwald", 
"eichwaldstraße", "einkaufszentrum", "einkaufszentrum (ekz)", "einnehmerei", "einsteinstraße", "eintracht", "eisenbahnstraße", "eisenhafengrund", "eisenstock", "eisinger straße", 
"eistreff", "eisweiher", "ekz", "elbinger straße ost", "elbinger straße west", "elchesheimer straße", "elfinger hof", "elfmorgenbruch", "ellental", "ellmendinger straße", 
"elsternweg", "emil-arheit-halle", "emil-gött-straße", "emilienruhe", "emilienstraße", "engel/höhenblick", "englerstraße", "entenfang", "entenhof", "entenstallhütte", 
"enzstraße", "eppinger straße", "erbersbronn", "erbprinz", "erdbeerweg", "erich-burger-heim", "erich-heckel-straße", "erlenbach", "erlenbach bei dahn", "erlenbacherstraße", 
"ermlisgrund", "ernst-barlach-straße", "ernstmühl", "ersingen west", "eschentalweg", "eschenweg", "esternaystraße", "ettlinger straße", "ettlinger tor", "eugen-geck-straße", 
"eugen-seelos-weg", "europahalle", "europaplatz", "europaplatz (kaiserstraße)", "europaplatz (karlstraße)", "europaplatz (spark)", "europaplatz (spark.)", "europe", "europäische schule", "eutinger straße", 
"eutzingerstraße", "eva-maria-buch-straße", "evangelische kirche", "extra-markt", "eyachbrücke", "fa argus", "fa behr", "fa heinrich", "fa lehr", "fa wolman", 
"fa. argus", "fa. behr", "fa. heinrich", "fa. lehr", "fa. wolman", "fa.nolte", "fabrik", "fachmarktzentrum", "falkenburg", "falkenstraße", 
"fanolte", "farrenstall", "fas-universität", "fassenteich", "feierabendweg", "feldbergstraße", "feldschlössle", "feldstraße", "felsenkeller", "felsentor", 
"fere-champenoise straße", "fernblick", "festhalle", "festplatz", "festspielhaus /alter bahnhof", "feuerwehr", "feuerwehrhaus", "fichtenstraße", "fikentscherstraße", "finanzamt", 
"fischkultur", "fischweier", "flachsteichweg", "flehinger straße", "fliederstraße", "florian-geyer-straße", "flughafenstraße", "flugplatz", "flürle", "flüsselweg", 
"forlenweg", "forschungsz bahnhof", "forschungsz busbf h", "forschungsz fiz", "forschungsz kbg", "forschungsz reak fr", "forschungsz südtor", "forschungsz wak", "forschungsz. bahnhof", "forschungsz. busbf. h", 
"forschungsz. fiz", "forschungsz. kbg", "forschungsz. reak. fr", "forschungsz. südtor", "forschungsz. wak", "forsthaus", "forsthaus heldenstein", "forsthaus taubensuhl", "forststraße", "fortmühlstraße", 
"fr-ebert-straße", "fr.-ebert-straße", "frankenthaler straße", "frankfurter straße", "frantzplatz", "franzbrücke", "franziska-höll schule", "frauenalb schielberg", "freibad", "freizeitparadies", 
"fridolin-stiegler-straße", "friedenshöhe", "friedensplatz", "friedensstraße", "friedenstraße", "friedhof", "friedhof obertal", "friedhof untertal", "friedhofstraße", "friedrich-ebert-straße", 
"friedrichschule", "friedrichshof", "friedrichshöhe", "friedrichsplatz", "friedrichstal", "friedrichstal (b fds)", "friedrichstal (b. fds)", "friedrichstraße", "fritz-erler-schule süd", "fruchthalle", 
"fröbelstraße", "fröhlichstraße", "fuchseck", "fächerbad", "fähranlegestelle", "fähre", "förch", "fürthstraße", "gabelsberger straße", "gaisbach", 
"gaishölle", "gallenbach", "gare", "gartenstraße", "gasthaus", "gasthaus auerhahn", "gasthaus blume", "gasthaus einsiedelhof", "gasthaus rebstock", "gasthaus rose", 
"gasthaus traube", "gasthaus weinberg", "gasthof talmühle", "gausbach", "gausplatz", "gaßeck", "gebersbergstraße", "gebhardstraße", "gehlmühle", "geigersberg", 
"geisbergstraße", "geisloch", "gemeindehalle", "gemeindezentrum", "gemminger straße", "gengenbach bahnhof", "gengenbachtal", "gerberastraße", "gerbersruhstraße", "germania", 
"germersheimer straße", "gernsbacher straße", "geroldsau heschmattweg", "geroldsäcker", "gertelbachstraße", "gewerbegebiet", "gewerbegebiet gröner", "gewerbepark", "gewerbepark cité", "gewerbestraße", 
"gewerbliches bildungsz", "gewerbliches bildungsz.", "glasersteg", "gleichmann", "gleishorbach", "gleiszellen", "glockwiesenstraße", "glogauer straße", "gluckstraße", "gochsheimer straße", 
"goethe-/bachstraße", "goethering", "goethestraße", "goldbergweg", "goldenes eck", "goldshaldenstraße", "golfplatz", "gompelscheuer", "goodyear", "gottesauer platz/bgv", 
"graf-berthold-straße", "graf-douglas-straße", "grashöhe", "grautenbach", "grenzstraße", "grenzsägmühle", "greschbachstraße", "griesbachstraße", "grimmerswaldstraße", "gritznerstraße", 
"groß-melten", "große dollenstraße", "große gasse", "großfischlingen", "großschneidersweg", "grund- und hauptschule", "grundschule", "gräfenhausen (pf) ort", "gräfenhausen ort", "gräfenhauser straße", 
"grässelmühle", "grötzenstraße", "grötzingen siedlung", "grüner baum", "grünewaldstraße", "grünwinkler straße", "gudrunstraße", "gustav-hofmann-straße", "gutenbergstraße", "gymnasium", 
"gärtnerei klingmann", "gölshausen", "gölshäuser lücke", "güterstraße", "haaberg mitte", "haardtstraße", "haardtweg", "habichtweg", "hadermark", "haftenring", 
"hagenbrück", "haguenauer straße", "hailerstraße", "halberstung", "hallenbad", "hallesche allee", "hambrücker straße", "hamburger straße", "hammann", "hammenweg", 
"hammweg", "hammäcker", "handelslehranstalt", "hans-bredow-straße", "hans-bredow-straße (swr)", "hans-thoma-schule", "hans-thoma-straße", "hansjakobstraße", "hardecksiedlung", "hardtsee", 
"hardtwald", "harmonie", "hartfeldschule", "haselweg", "haslach bahnhof", "haslacher straße", "hauffstraße", "hauptbahnhof", "hauptbahnhof/zob", "hauptfeld", 
"hauptfriedhof", "hauptpost", "hauptschule", "hauptstraße", "hauptstraße/rohrgasse", "haus bethlehem", "haus glaser", "haus könig", "haus oser", "haus planeck", 
"haus reich", "haus roth", "haus schneider", "haus seifried", "haus wasserfall", "hausener straße", "haydnstraße", "hbf bahnhofsvorplatz", "hbf busbahnhof mitte", "hbf busbahnhof nord", 
"hbf busbahnhof süd", "hebel", "hebelweg", "heckenäcker", "hedwigshof", "heerstraße", "heide", "heidehof", "heidelberger ring", "heidelsheim nord", 
"heilbronner straße", "heimatmuseum", "heimig", "heimschule lender", "heller", "henri-dunant-platz", "herdstraße", "hergersweiler ort", "herrengut", "herrenstraße", 
"hertweg", "hertzstraße", "herweghstraße", "heselbach", "hessenstraße", "hessestraße", "hetschelhof", "heuweg", "hilpertsau", "hilschweiher", 
"hindenburgplatz", "hindenburgstraße", "hinterlangenbach", "hinterseebach", "hinterseebach adler", "hirsch", "hirschbach", "hirschhornstraße", "hirschwinkelbrunnen", "hirschwinkelhütte", 
"hirtenbrunnen", "hirtenweg/technologiepark", "hl-kreuz-kirche", "hl.-kreuz-kirche", "hochhaus", "hochries", "hochstetten", "hochstraße", "hocircumflexpital", "hohberg", 
"hohberghaus", "hohe steige", "hohenäckerallee", "hohlgasse", "hohritt", "hohwald", "holbeinstraße", "holdereck", "holtzstraße", "holzbachstraße", 
"holzgasse", "horbachpark", "hornisgrinde", "hornisgrindestraße", "horststraße", "horstweg", "hotel post", "hub", "hubertusbrücke", "hubstraße", 
"hugo-junkers-straße", "hummelberg", "hundseck", "husarenlager", "huttenheimer straße", "huttenkreuzstraße", "huzenbach", "händelstraße", "häsel", "häusleäcker", 
"höfener straße", "höhenstraße", "höhenwellenbad", "hörchenberg", "hörden", "hördter straße", "hübschstraße", "hügellandstraße", "hüttenbrunnen", "illenkreuz", 
"im eichbäumle", "im fritschengärtel", "im grün", "im grüner", "im heizler", "im kleinen bruch", "im kloth", "im neufeld", "im oberwald", "im rüsten", 
"im saalbrett", "im sand", "im steingerüst", "im stöck", "im wöhr", "immenstein", "in den bruchwiesen", "in der halde", "industrie", "industrieg hasenstock", 
"industrieg. hasenstock", "industriegeb königstraße", "industriegeb. königstraße", "industriegebiet", "industriegebiet köbler", "industriestraße", "industriestraße/l", "ispringer staffel", "ittersbacher straße", "ittlinger straße", 
"j s bach straße", "j. s. bach straße", "jagdhausstraße", "jahnhalle", "jahnstraße", "jakob-dörr-straße", "jenaer straße", "jkg", "jockgrim", "johanna-kirchner-straße", 
"johanneskirche", "johannesplatz", "josef-heid-straße", "josef-kilmarx-straße", "josef-schofer schule", "josef-stöhrer-weg", "josefstraße", "joß-fritz-schule", "jugendhaus", "jugendheim", 
"jugendherberge", "jugendzentrum", "julius-bender-straße", "jungfernsprung", "junker-u-ruh-straße", "junker-u.-ruh-straße", "jägerhaus", "jägerhof", "jägerstraße", "jägerstüble", 
"jöhlinger straße", "kaiser-wilhelm-straße", "kaiserbacher mühle", "kaisereck", "kaisermühle", "kaiserslauterner straße", "kaiserstraße", "kalkstatt", "kalmit", "kaltenbach", 
"kaltenbronn", "kaltenbrunnen b", "kaltenbrunnen l", "kapelle", "kapellenstraße", "kaplaneihof", "karl-berberich-schule", "karl-delisle-straße", "karl-leopold-straße", "karl-späth-straße", 
"karl-weysser-straße", "karl-wilhelm-platz", "karlhäuser hof", "karlsbader straße", "karlsruher straße", "karlstor", "karlstraße", "kath kindergarten", "kath kirche", "kath. kindergarten", 
"kath. kirche", "katharinentaler hof", "katholische kirche", "katholisches pfarramt", "kehle", "kehler straße", "kehlstraße", "kelter", "keltergasse", "kelterplatz", 
"kerweplatz", "kesselstraße", "kettenbrücke", "kiefernweg", "kieselbronner straße", "kieselweg", "kiesstraße", "killisfeld", "killisfeldstraße", "kinderdorf", 
"kindergarten", "kindergarten vormberg", "kinzigstraße", "kirchbühlstraße", "kirche", "kirche/lauferstraße", "kirche/schule", "kirchenplatz", "kirchfeld", "kirchfeld fortuna", 
"kirchgassweg", "kirchhäuser weg", "kirchplatz", "kirchstraße", "kirschbaumwasen", "kl plom/assek herrmann", "kl. plom/assek. herrmann", "kleine dollenstraße", "kleiner muck", "kleines feldlein", 
"kleinfischlingen", "kleinwildbad", "klingen", "klingen (heuchelheim)", "klingenbach", "klinik dr.dengler", "klinik drdengler", "klinikum", "kloster", "klosterbrücke", 
"klostergarten", "klostergut", "klosterhof", "klosterplatz", "klotzberg", "klotzbergstraße", "kläranlage", "knielinger allee", "knittelsheim", "knittlinger straße", 
"kohlerstal", "kohlhäusle", "kolbengärten", "kolberger straße", "kolonie", "kolpingplatz", "kongresszentrum", "konrad-adenauer-platz", "konrad-adenauer-str", "konrad-adenauer-straße", 
"konzerthaus", "kraichgaustraße", "kraichtalstraße", "krankenhaus", "krankenhaus siloah", "krankenhaus/b", "krappmühlenweg", "kreisberufsschule", "kreisel", "kreisschulzentrum", 
"kreisverwaltung", "kreuz", "kreuzbergsee", "kreuzle", "kreuzstraße", "kreuzung", "kreuzäcker", "kriminalpolizei", "kronauer allee", "kronauer straße", 
"krone", "kronenplatz", "kronenplatz (fritz-erler-straße)", "kronenplatz (kaiserstraße)", "kronprinzenstraße", "kropfinger", "kuhardt", "kullenmühle", "kulturhaus osterfeld", "kulturtreff", 
"kunstakademie / hochschule", "kupferhammer", "kupferhälde", "kuppenheimer straße", "kurfürstenstraße", "kurhaus", "kurhaus/etzenroter straße", "kurmittelhaus", "kurpark", "kurpfalzstraße", 
"kurt-schumacher-straße", "kußmaulstraße", "kämpfelbachquelle", "kändelweg", "käppele", "kärcherstraße", "käthe-kollwitz-schule", "käthe-kollwitz-straße", "köhlerweg", "königsbacher straße", 
"königsberger straße", "kübelmarkt", "kühler krug", "kürnbacher straße", "l/allee", "lameyplatz", "lamm", "lammstraße", "landauer straße", "landeckstraße", 
"landesbausparkasse", "landgrabenstraße", "landratsamt", "landstraße", "langenacker", "langenscheider hof", "langenwaldsee", "langgewannstraße", "langwiesenstraße", "lassallestraße", 
"laube", "lautenhof", "lauterbourg", "lauterburger straße", "lauterschwan", "lebenshilfe", "leiberstunger straße", "leinsweilerhof", "leintalschule", "leislingstraße", 
"leopoldplatz", "leopoldshafener straße", "leopoldsplatz", "leopoldstraße", "lerchenberg", "lerchenbergweg", "lerchenweg", "lessingstraße", "lichtental", "lichtental brahmsplatz", 
"lichtental höllhäuserweg", "lichtentaler allee/museen", "liebenzeller straße", "liebfrauenkirche", "liebigstraße", "liedolsheimer straße", "liehenbachkapelle", "liehenbachstraße/seniorenz", "liehenbachstraße/seniorenz.", "lilienmattstraße/drk-klinik", 
"lilienthalstraße", "limburgstraße", "limburgstraße (kirche)", "linde", "lindenallee", "lindenplatz", "lindenstraße", "lindenweg", "linkenheimer tor", "linkenheimer weg", 
"liststraße", "lisztstraße", "litzlunger straße", "liverdunplatz", "lochfeldstraße", "lochweg", "lolosruhe", "lolosruhe (schänzel)", "lorenzstraße/zkm", "lortzingstraße", 
"ludwig thomastraße", "ludwig wilhelm stift", "ludwig-erhard-straße", "ludwigsplatz", "luisenstraße", "luitpoldstraße", "luk", "luk (dieselstraße)", "lutherstraße", "lutz", 
"lußstraße", "lvk-schule", "lyzeumstraße", "lärchenweg", "löwen", "löwen-apotheke", "löwenplatz", "lützowerstraße", "madenburgweg", "mahdwiesenhof", 
"mahler", "maierhof", "maihälden", "malschbach", "malschbacher straße", "malscher straße", "malzfabrik", "mannheimer straße", "maria halden", "maria linden", 
"maria-ward-schule", "markgrafenplatz", "marktplatz", "marktplatz (kaiserstraße)", "marktplatz (pyramide)", "marktplatz/post", "marktplatz/rathaus", "marktplatz/stadthaus", "marktstraße", "markwaldhütte", 
"martin", "martin-luther-straße", "martin-luther-straße/arndtstraße", "marxstraße", "mathystraße", "matthäuskirche", "mauerweg", "maulbronner straße", "max-beckmann-straße", "max-dortu-straße", 
"max-jäger-schule", "max-liebermann-straße", "maxau", "maximilianstraße", "maximilianstraße/falkenstraße", "maybachstraße", "mayersbild", "maystraße", "medersbuckel", "mehliskopf", 
"mendelssohnpl./röser haus", "mendelssohnpl/röser haus", "merceau", "mercedes süd", "mercedes-benz werk", "mercedes-benz werk hauptst", "mercedes-benz werk hauptst.", "merkurschule", "merkurstraße", "merkurwald", 
"messe/leichtsandstraße", "meßplatz", "michael-beheim-schule", "michelbacher straße", "milchhaus", "milchhof", "minderslachen", "mitte", "mittelenztal", "mittelhambach", 
"mittellangenbach", "mittelplatz", "mittelstraße", "mitteltorstraße", "moby dick", "modenbacher hof", "moldaustraße", "molkerei", "moltkestraße/rosengarten", "mona", 
"monbach-neuhausen", "monbachtal", "monmouthplatz/kurhaus", "moosbronner straße", "mooser straße", "mozartstraße", "mozartweg", "muckenschopf", "mulde", "multimarkt", 
"mummelsee", "murgtaler straße", "murgtalstraße süd", "muthstraße", "mähfeldstraße", "möbel voos", "mörscher straße", "mörzheimer straße", "mühlbacher straße", "mühlburg west", 
"mühlburger feld", "mühlburger tor", "mühlenweg", "mühlhausener straße", "mühlhofen", "mühlplatz", "mühlrain", "mühlstraße", "müllhofen", "münchener straße", 
"münchfeldsiedlung", "münchfeldstraße", "münchhofstraße", "münchweiler", "narzissenstraße", "neckar turm", "neckarplatz", "nelkenstraße", "neuapostolische kirche", "neudorf", 
"neue anlage straße", "neue schule", "neue wiesen", "neuenbürger straße", "neuenwegstraße", "neuer messpl./Ärzteh.", "neuer messpl/Ärzteh", "neuer messplatz/sbk", "neues schloß", "neuhaus", 
"neuhof", "neukauf", "neulauterburg", "neulinger wald", "neumalsch", "neumühle", "neureuter hauptstraße", "neureuter straße", "neustadter straße", "neutorstraße", 
"neuwiesenreben", "neuwiesenstraße", "neßlerstraße", "niederbühler tor", "niederfeld", "niederhofen", "niederschlettenbach", "niederwaldstraße", "nikolaus-moll-straße", "nobelstraße", 
"nord", "nord-west", "nordbahnhof", "nordring", "nußbaumer straße", "nußbaumstraße", "nußbaumweg", "nöttinger straße", "nürnberger straße", "o-frey-straße", 
"o-haefelin-/p-fischer-straße", "o.-frey-straße", "o.-haefelin-/p.-fischer-straße", "ober-tor-platz", "oberausstraße", "oberbeuern", "oberdorf", "oberdorfstraße", "obere breite", "obere büchelbach", 
"obere dorfstraße", "obere fahlbrücke", "obere hauptstraße", "obere kullenmühle", "obere langgasse", "obere prinz-weimar-straße", "obere schußbach", "obere steinbeisstraße", "oberer haaberg", "oberer mocken", 
"oberer mühlweg", "oberes gaistal", "oberfeld", "oberfeldstraße", "oberhambach", "oberhof", "oberhofen", "obermühlstraße", "obernhausen", "oberotterbach", 
"oberschlettenbach", "obertorplatz", "oberwaldstraße", "oberwiesenhof", "obsthof", "ochsen", "ochsentorstraße", "oesterle", "offenbacher straße", "ohmstraße", 
"oktorfeld", "ooswinkel", "oranger platz", "orgelfelsenhaus", "ort", "ortseingang", "ortsmitte", "ortsstraße", "ortsverwaltung", "ost", 
"ostbahnhof", "ostendorfplatz", "ostendstraße", "ostenstraße", "osteroder straße", "ostmarkstraße", "ostring", "oswald-zobel-straße", "ottenhofener straße", "ottilienberg", 
"otto-flake-straße", "otto-hahn-straße", "otto-muck-straße", "otto-sachs-straße", "ottostraße", "p-gerhardt-straße", "p.-gerhardt-straße", "pandurenbronn", "panoramastraße", "paracelsusklinik", 
"paradeplatz", "pariser platz", "parkanlage", "parkdeck", "parkhaus zentrum", "parkschlößle", "parkstift", "parkstraße", "pastor-felke-straße", "paul-rein-straße", 
"paulus stift", "pavillon", "penny markt", "pestalozzischule", "petergraben", "pfaffenroter straße", "pfalzgrafenstraße", "pfalzhof", "pfalzklinikum", "pfarrer-hamm-platz", 
"pfarrhaus", "pfarrzentrum", "pfefferäcker", "pfeilerstraße", "pfinzbrücke", "pfinzhof", "pfinzstraße", "pfinztalstraße", "pfizer", "pforzheimer straße", 
"pfrommer", "pfrondorfer mühle", "pfälzer hof", "pfälzer straße", "pfühlpark", "philippsburger straße", "philippstraße", "pleisweiler", "plöck", "polizei", 
"post", "post / gleisslestraße", "postgraben", "postgrabenstraße", "posthius-/hans-sachs-straße", "postplatz", "poststraße", "printzstraße", "prinz carl", "prätoriusstraße", 
"pulverturm", "quettigstaffeln", "r v schmauß straße", "r-koch-straße/bachschloßweg", "r. v. schmauß straße", "r.-koch-straße/bachschloßweg", "radeburger straße", "raiffeisen", "raiffeisenbank", "raiffeisenplatz", 
"raiffeisenstraße", "rangierbahnhof", "rankhütte", "rappen", "rappenwört", "rastatter straße", "rasthof ost", "rasthof west", "rathaus", "rathaus (bus)", 
"rathaus (drei-tore-straße)", "rathaus (friedrichstraße)", "rathaus (schwarzwaldstraße)", "rathaus ii", "rathausmarkt", "rathausplatz", "rathausstraße", "ratz", "rauentaler straße ost", "rauentaler straße west", 
"raumünzach", "real-/hauptschule", "realschule", "rebgärtenstraße", "rebland", "rebstock", "rebstöckl", "rechberg", "rechbergklinik", "rechtenbach", 
"reetzstraße", "reha-zentrum", "rehteich", "reihener straße", "reinmuthstraße", "reisdorf", "reiterhof", "reitschulschlag", "reitschulschlag schleife", "remonte", 
"rendezvous", "rennbahnstraße", "rennfeld", "rentschler", "rettigheimer straße", "reute", "rheinau nord", "rheinauer gärtle", "rheinauer kirchweg", "rheinauer ring", 
"rheinaustraße", "rheinaustraße (b)", "rheinbergstraße", "rheinbergstraße wendeschleife", "rheinfähre", "rheinhafen", "rheinhafenstraße", "rheinstraße", "rheintalschule", "rheintalstraße", 
"rheintorstraße", "rheinzabern", "rheumazentrum", "richard-hecht-schule", "richard-strauß-straße", "richard-wagner-ring", "riedstraße", "riehtstraße", "rieslingstraße", "rimmelsbacher hof", 
"ringelberghohl", "ringstraße", "rinklingen", "rintheim", "rintheimer querallee", "rintheimer straße", "ritterhof", "rittersbach", "robert-koch-straße", "rohnbach", 
"rohräckerstraße", "roller", "rommelstraße", "rose", "rosengarten", "rosenhofstraße", "rosenweg", "rosmarinweg", "rote kaserne", "rote lache", 
"rotenbach", "rotenbach (enz)", "rotenberger hof", "rotenbächle", "rotes haus", "roßweide", "rudolf-breitscheid-straße", "rudolf-plank-straße", "ruhestein", "ruiter straße", 
"rupprechtschule", "rupprechtstraße", "rödereckring", "röhrbrunnen", "römer wachstube", "römerstraße", "röntgenstraße", "rösselsbrünnle", "röt b/ab schönegr", "röt b/ab. schönegr.", 
"röttererbergstraße", "rötzweg", "rößle", "rößlesweg", "rülzheimer straße", "saarstraße", "safrangarten", "saint-riquier-platz", "salierstraße", "salinenstraße", 
"sallenbusch", "salmen", "salzbrunnenstraße", "sand kapelle", "sandgrube", "sandweg", "sauersbosch", "sbk-markt", "schafackerstraße", "schafhofweg", 
"schafplatz", "schauinslandstraße", "scheck-in", "schefenacker", "scheffelstraße", "scheibenh straße", "scheibenh. straße", "scherer", "scherrhof", "scherrngasse", 
"scherzenteich", "scheuelberghof", "schielenswald", "schießhüttenäcker", "schiff", "schiftung", "schillergymnasium", "schillerpark", "schillerschule", "schillerstraße", 
"schillerstraße (kaiserallee)", "schindelberg", "schindelbronn", "schindele", "schindelpeter", "schirlingsgarten", "schirmhofweg", "schlachthaus", "schlachthof", "schlattstraße", 
"schlesier straße", "schlesier straße (ost)", "schlesier straße (west)", "schlettstadter straße", "schliffkopf", "schloss", "schloss rüppurr", "schlossbergring", "schlossplatz", "schloß", 
"schloß ludwigshöhe", "schloß stutensee", "schloßgarten", "schloßgartenhalle", "schloßpark", "schloßstadion", "schloßstraße", "schluttenbacher straße", "schlössel", "schmalbach", 
"schmelzerbrücke", "schmiegrankweg", "schmuckmuseum", "schneckenbach", "schneckentalweg", "schneidemühler straße", "schottmüllerstraße", "schreinerei rapp", "schröderstraße", "schubertstraße", 
"schule", "schule/halle", "schulhaus", "schulstraße", "schulstraße/penny", "schulz./panoramabad", "schulz/panoramabad", "schulzentrum", "schulzentrum dachgrube", "schulzentrum ost", 
"schumannstraße", "schußbachstraße", "schw-baptista-straße", "schw.-baptista-straße", "schwabenbrücke", "schwabenstraße", "schwabentorhalle", "schwanen", "schwanenwasen", "schwanenweiher", 
"schwanheim", "schwanheim (pfalz)", "schwarzenbach", "schwarzenbachtalsperre", "schwarzenkopf", "schwarzer weg", "schwarzerdhof", "schwarzmißhütte", "schwarzwaldhochstraße", "schwarzwaldhof", 
"schwarzwaldschule", "schwarzwaldstraße", "schwarzwasen", "schwegenheimer hof", "schweigener straße", "schweigrother platz", "schweriner straße", "schwetzinger straße", "schwimmbad", "schwimmschulweg", 
"schäferstraße", "schänzel", "schänzel (palatinabus)", "schömberger straße", "schönbiegel", "schönblick", "schönblickstraße", "schönbornstraße", "schönbüch", "schützen", 
"schützenhaus", "schützenkreuz", "seehausweg", "seelhof", "seestraße", "seewaldstraße", "seibelseckle", "seniorenheim", "seniorenzentrum", "sew", 
"shopping cité", "siedlung", "siedlungsstraße", "siemens", "siemens wohnheim", "siemens-/oberv-haefelin-str", "siemens-/oberv.-haefelin-str", "siemensallee", "siemensstraße", "silberaustraße", 
"silberhölle", "silcherschule", "silcherstraße", "sinner", "sinner (durmersh straße)", "sinner (durmersh. straße)", "sinner (zeppelinstraße)", "sinsheim-museum", "sinsheimer straße", "sinzheimer straße", 
"sixtdenkmal", "smg", "smiley barracks", "sohl", "solmsstraße", "sommerfeldstraße", "sommerhalde", "sonne", "sonnenapotheke", "sonnenberg", 
"sonnenbrunnen", "sonnenbühl", "sonnenstraße", "sophienstraße", "sparkasse", "sparkassenschule", "spechtschmiede", "speiertsgasse", "speiglerstraße", "speyerer straße", 
"spielberg", "spinnerei", "spitzacker", "spitzackerweg", "sponeck kaserne", "sporgasse", "sporthalle", "sportplatz", "sportplatzstraße", "sportplatzweg", 
"sportzentrum", "sprangerweg", "sprantal", "sprollenmühle", "spöcker straße", "spöcker weg", "st aurelius", "st barbara", "st germanshof", "st johann (pfalz)", 
"st josefs-kirche", "st martin ort", "st martiner straße", "st paulus-stift", "st vincentius krankenhaus", "st. aurelius", "st. barbara", "st. germanshof", "st. johann", "st. johann (pfalz)", 
"st. josefs-kirche", "st. martin ort", "st. martiner straße", "st. paulus-stift", "st. vincentius krankenhaus", "st.paul", "staatsstraße/aldi", "stachus", "stadelhoferstraße", "stadion", 
"stadionstraße", "stadt", "stadtbahnhof", "stadtbibliothek", "stadtfriedhof", "stadtgrenze", "stadthalle", "stadtkirche", "stadtklinik", "stadtmitte", 
"stadtverwaltung", "stadtwerke", "staigstraße", "starckstraße", "staufenbergweg", "stauweiher", "steckenhalt", "stefanstraße", "stegwiesen", "steiermärker straße", 
"steigweg", "stein", "stein (pfalz)", "steinach bahnhof", "steinachweg", "steinackergasse", "steinackerstraße", "steinberggutstraße", "steinbruch", "steingasse", 
"steinplatz", "steinstraße", "stephanienbad", "sternen", "sternenfelser straße", "stettfelder straße", "stierlenwerke", "storaenso", "storchentor", "storrenacker mitte", 
"storrenacker nord", "storrenacker süd", "stpaul", "straubenhöfe", "strauß", "straßburger straße", "straßenmeisterei", "streibelgrund", "stresemannstraße", "strohhütte", 
"strombergstraße", "studentenhaus", "stuttgarter straße", "städt klinikum moltkestraße", "städt krankenhaus", "städt. klinikum moltkestraße", "städt. krankenhaus", "stöckach", "störrhof", "sudetenstraße", 
"sulzbach", "sulzbacher straße", "synagoge", "sägemühle", "sägmühlweg", "sägwasenplatz", "sängerheim", "säuterich", "süd", "südbahnhof", 
"südendschule", "südring", "südstadt", "tabakschopf", "taglöhnergärten", "tal", "talblickstraße", "talstraße", "talweg", "talwiese", 
"talwiesenweg", "tankstelle", "tankstelle huck", "tankstelle jäger", "tannenweg", "taubenäckersiedlung", "tauchert", "teeuwen", "teich/wanne", "tell", 
"tennisplätze", "theobald-/august-keiler-straße", "theodor-heuss-straße", "thermalbad", "thermarium", "thomas-mann-straße", "thomas-nast-hochhaus", "thomashof", "tiefbauamt", "tiefenauer straße", 
"tiefentalstraße", "tiefer weg", "tiergarten/korbmattfelsenh", "tiergarten/korbmattfelsenh.", "tierpark", "tivoli", "tolna-platz", "tonwerk", "torwingert", "trappensee", 
"trierer straße", "trifelsstraße", "tullahalle", "tullastraße", "tulpenstraße", "tunnelstraße", "turmberg", "turmbergbad", "turnhalle", "tÜv", 
"ubstadt-weiher", "ubstadt-weiher (db)", "uhlandplatz", "uhlandstraße", "ullrichsbruch", "ulmenstraße", "umweger straße", "universität", "universität/meßplatz", "unterdorf", 
"untere au", "untere bahnhofstraße", "untere breitstraße", "untere büchelbach", "untere hauptstraße", "untere prinz-weimar-straße", "untere wiesen", "unterer brühl", "unteres kreuz", "untermühlstraße", 
"unterstmatt", "unterwasser", "us-depot", "venningen", "verbandsgemeinde", "versorgungsamt", "verwaltungsstelle", "victoriastraße", "videothek", "viehläger abzw biberkessel", 
"viehläger abzw. biberkessel", "viehläger wendeplatz", "viermorgen", "viertelstraße", "villa rustica", "vimbucher straße", "vincent krankenhaus", "vincent. krankenhaus", "vogelsangstraße", "vogesenbrücke", 
"vogesenstraße", "voglergasse", "volksbank", "volksgarten", "volkshochschule", "vollmersweiler ort", "vorderlangenbach", "vorderweidenthal", "w-münsterplatz", "w-störk-straße", 
"w.-münsterplatz", "w.-störk-straße", "waage", "wachhausstraße", "wackershofen", "wackerstraße", "waidweg", "waldbrücke", "waldcafé", "waldeck", 
"waldecker hof", "waldenserkirche", "waldfriedhof", "waldhambach", "waldhaus", "waldhohl", "waldhorn", "waldkapelle", "waldklinik", "waldluft", 
"waldmattstraße", "waldorfschule", "waldpark", "waldparkplatz", "waldprechtsweier", "waldrohrbach", "waldseebad", "waldseestraße/verfassungsplatz", "waldsportpfad", "waldstraße", 
"walzbachhalle", "wannenweg", "wartberg", "wartbergstraße", "warte", "wasen", "wasserfall", "wasserfälle", "wasserreservat", "wasserwerk", 
"wattkopfstraße", "wehrstraße", "weidbruch", "weidfeld", "weiherberg", "weiherbergstraße", "weiherhof", "weiherstraße", "weiherweg", "weiler", 
"weinbergstraße", "weinbrenner straße", "weinbrennerplatz", "weinbrennerstraße", "weingartener straße", "weinstraße", "weinstraße nord", "weinstube Übel", "weintor", "weinweg", 
"weitenruß", "weitenunger straße", "weißenburger straße", "weißer stein", "weißes haus", "welfenstraße", "welschhof", "welschneureuter straße", "wendelinusstraße", "wendelrot", 
"wendeplatte", "werderstraße", "werkstraße", "wernerswingert", "west", "westbahnhof", "westendstraße", "westlicher krebspfad", "westring", "westring nord", 
"wette", "weyhererstraße", "wiedenbach", "wiedenfelsen", "wiesengrund", "wiesenstraße", "wiesental", "wiesentalstraße", "wiesenweg", "wildpark", 
"wilfenberg", "wilferdinger straße", "wilgartishalle", "wilhelm-drapp-straße", "wilhelm-kolb-straße", "wilhelm-leuschner-straße", "wilhelm-schech-straße", "wilhelmshöhe", "wilhelmstraße", "windeckstraße", 
"winden jagdhausstraße", "winden schulhof", "windhof", "windschläger straße", "winkel", "winkelberg", "wintereck", "winterrot", "winzergenossenschaft", "witstunger straße", 
"witthumanlage/simmelturm", "wohnlichstraße", "wolfartsweierer straße", "wolfhagweg", "wolfsbaum", "wolfsbergallee", "wolfseck", "wolfsschlucht", "wollmesheimer höhe", "wolsbrunnen", 
"wurstberg", "wässergraben", "wörtel", "wörtelstraße", "wörth", "wörthstraße", "würmersheimer straße", "württemberger straße", "xylanderstraße", "yburgstraße", 
"yburgstraße/sportschule", "yorckstraße", "zaystraße", "zehntstraße", "zeiligstraße", "zellmarkstraße", "zeltplatz", "zentrum", "zeppelinstraße", "zickstraße", 
"zieflesberg", "ziegelei", "ziegelhütte", "ziegelsteigle", "zimmern", "zimmerplatz", "zinken", "zkm", "zob", "zob bahnhof", 
"zollhaus", "zoo", "zoo (abzw uni)", "zoo (abzw. uni)", "zuflucht", "zum bahnhof", "zum kleinen feld", "zum mütterle", "zur hohe loog", "zur pfalz", 
"zur samsruhe", "zwickgabel", "zylinderhof", "zündhütle", "Äußere dietlinger straße", "Äußere hirsauer straße", "Ölbronn stadtbahn", "Ötigheimer weg", "Ötisheimer steige", "Ötisheimer straße"
);
